# Generated by Django 5.1.4 on 2026-05-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_camporegla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campopersonalizado',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Campo personalizado', 'verbose_name_plural': 'Campos personalizados'},
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='alcance',
            field=models.CharField(choices=[('leads', 'Solo Leads'), ('clientes', 'Solo Clientes'), ('ambos', 'Leads y Clientes')], default='ambos', max_length=20, verbose_name='Aplica a'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='opciones',
            field=models.JSONField(blank=True, default=list, verbose_name='Opciones (para Lista)'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='requerido',
            field=models.BooleanField(default=False, verbose_name='Requerido'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, unique=True, verbose_name='Clave interna'),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Texto libre'), ('numero', 'Número'), ('fecha', 'Fecha'), ('booleano', 'Sí / No'), ('lista', 'Lista de opciones')], default='texto', max_length=20, verbose_name='Tipo'),
        ),
    ]
