# Generated by Django 5.1.4 on 2026-05-29 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_remove_automatizacionlog_unique_regla_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automatizacionlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='automatizacionlog',
            name='evento',
            field=models.CharField(blank=True, help_text='Descripción del evento que disparó (para event-based)', max_length=200),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='accion_agente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatizaciones_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Agente a asignar'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='accion_mensaje_texto',
            field=models.TextField(blank=True, help_text='Podés usar {lead}, {estado}, {telefono}', verbose_name='Texto del mensaje'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='accion_webhook_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='URL del webhook'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='trigger_campo',
            field=models.CharField(blank=True, default='estado', help_text='Campo del lead (ej: estado, prioridad)', max_length=50, verbose_name='Campo que cambia'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='trigger_valor_anterior',
            field=models.CharField(blank=True, help_text='Dejar vacío para "cualquier valor anterior"', max_length=100, verbose_name='Valor anterior'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='trigger_valor_nuevo',
            field=models.CharField(blank=True, help_text='Valor al que cambia el campo', max_length=100, verbose_name='Valor nuevo'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_tarea_descripcion',
            field=models.TextField(blank=True, help_text='Podés usar {lead} para el nombre del lead.', verbose_name='Descripción de la tarea'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_tarea_dias_plazo',
            field=models.PositiveSmallIntegerField(default=1, help_text='Días desde hoy para la tarea', verbose_name='Plazo (días)'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_tipo',
            field=models.CharField(choices=[('cambiar_estado', 'Cambiar estado del lead'), ('cambiar_prioridad', 'Cambiar prioridad del lead'), ('enviar_plantilla_wa', 'Enviar plantilla de WhatsApp'), ('crear_tarea', 'Crear tarea para el agente asignado'), ('enviar_mensaje_wa', 'Enviar mensaje de WhatsApp (texto libre)'), ('asignar_agente', 'Asignar agente al lead'), ('llamar_webhook', 'Llamar webhook externo (n8n / URL)')], max_length=30, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='trigger_dias',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de días (solo para disparadores por tiempo)', null=True, verbose_name='Días'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='trigger_tipo',
            field=models.CharField(choices=[('tiempo_desde_creacion', 'N días desde que ingresó el lead'), ('tiempo_sin_cambio', 'N días sin actividad en el lead'), ('tiempo_sin_respuesta_wa', 'N días sin respuesta de WhatsApp del cliente'), ('estado_cambio', 'Cuando un campo del lead cambia de valor')], max_length=30, verbose_name='Disparador'),
        ),
    ]
