# Generated by Django 5.1.4 on 2026-05-29 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_event_based_triggers'),
        ('leads', '0009_alter_campopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatizacionlog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automatizacion_logs', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='accion_tipo',
            field=models.CharField(choices=[('cambiar_estado', 'Cambiar estado del lead'), ('cambiar_prioridad', 'Cambiar prioridad del lead'), ('enviar_plantilla_wa', 'Enviar plantilla de WhatsApp'), ('crear_tarea', 'Crear tarea para el agente asignado'), ('enviar_mensaje_wa', 'Enviar mensaje de WhatsApp (texto libre)'), ('asignar_agente', 'Asignar agente al lead'), ('llamar_webhook', 'Llamar webhook externo (n8n / URL)'), ('convertir_cliente', 'Convertir lead a Cliente automáticamente')], max_length=30, verbose_name='Acción'),
        ),
    ]
