# Generated by Django 5.1.4 on 2026-06-08 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0004_convertir_cliente_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='delay_cantidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='delay_unidad',
            field=models.CharField(blank=True, choices=[('minutos', 'Minutos'), ('horas', 'Horas'), ('dias', 'Días')], default='dias', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='fecha_campo_objetivo',
            field=models.CharField(blank=True, help_text='Campo del lead, ej: fecha_nacimiento, created_at', max_length=50, verbose_name='Campo de fecha'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='fecha_campo_offset_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Offset (días)'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='fecha_campo_offset_signo',
            field=models.CharField(blank=True, choices=[('antes', 'antes de'), ('despues', 'después de')], default='despues', max_length=10, verbose_name='Offset'),
        ),
        migrations.AddField(
            model_name='reglaautomatizacion',
            name='tipo_regla',
            field=models.CharField(choices=[('automatizacion', 'Automatización'), ('disparador', 'Disparador')], db_index=True, default='automatizacion', max_length=15, verbose_name='Tipo de regla'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='trigger_campo',
            field=models.CharField(blank=True, default='estado', help_text='Campo del lead a observar (ej: estado, prioridad, agente)', max_length=50, verbose_name='Campo'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='trigger_dias',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Para "N días sin actividad" / "N días sin respuesta de WhatsApp"', null=True, verbose_name='Días'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='trigger_tipo',
            field=models.CharField(choices=[('inmediato', 'Inmediatamente (al cumplirse la condición)'), ('delay', 'En X tiempo'), ('fecha_campo', 'Cuando un campo de fecha coincide con una referencia'), ('tiempo_sin_cambio', 'N días sin actividad en el lead'), ('tiempo_sin_respuesta_wa', 'N días sin respuesta de WhatsApp del cliente'), ('creado', 'Al crear el lead'), ('campo_cambia', 'Cuando un campo cambia (a cualquier valor nuevo)'), ('campo_igual_a', 'Cuando un campo pasa a valer un valor específico'), ('responsable_cambia', 'Cuando cambia el responsable (agente) del lead')], max_length=30, verbose_name='Disparador'),
        ),
        migrations.AlterField(
            model_name='reglaautomatizacion',
            name='trigger_valor_nuevo',
            field=models.CharField(blank=True, help_text='Valor al que debe cambiar el campo', max_length=100, verbose_name='Valor nuevo'),
        ),
        migrations.CreateModel(
            name='CondicionRegla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('campo', models.CharField(help_text='ej: estado, prioridad, origen, agente, plan_interes, cp:<slug>', max_length=50, verbose_name='Campo')),
                ('operador', models.CharField(choices=[('eq', 'es igual a'), ('neq', 'no es igual a'), ('gt', 'mayor que'), ('lt', 'menor que'), ('contains', 'contiene'), ('empty', 'está vacío'), ('not_empty', 'no está vacío')], default='eq', max_length=12, verbose_name='Operador')),
                ('valor', models.CharField(blank=True, max_length=200, verbose_name='Valor')),
                ('join_siguiente', models.CharField(choices=[('AND', 'Y'), ('OR', 'O')], default='AND', help_text='Cómo se combina con la condición que sigue (Y / O)', max_length=3, verbose_name='Unión con la siguiente')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='automations.reglaautomatizacion')),
            ],
            options={
                'verbose_name': 'Condición de regla',
                'verbose_name_plural': 'Condiciones de regla',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
