# Generated by Django 5.1.4 on 2026-05-29 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campana_clientes_support'),
        ('leads', '0009_alter_campopersonalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='contactos_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='Leads seleccionados'),
        ),
        migrations.AlterField(
            model_name='campana',
            name='filtros_segmento',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='campana',
            name='variables_mapping',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='campanalog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.lead'),
        ),
    ]
